spring:
  application:
    name: finanzasPersonales
logging:
  level:
    com: ${LOGGING_LEVEL}
datasource:
  url: ${DATASOURCE_URL}
  username: ${DATASOURCE_USERNAME}
  password: ${DATASOURCE_PASSWORD}
  driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
jpa:
  database-platform: ${DATASOURCE_PLATFORM}
  show-sql: true
  hibernate:
    ddl-auto: update
h2:
  console:
    enabled: true
    path: /h2-console




